services:
  - type: web
    name: cv-maker
    env: python
    pythonVersion: 3.9
    buildCommand: |
      echo "Disabling ReportLab C extensions"
      export REPORTLAB_NO_ACCEL=1
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
